version: '3.8'

services:

  pocketbase:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pb_data:/pb/pb_data

  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/app/www
    depends_on:
      - pocketbase
